# Generated by Django 5.2.15 on 2026-06-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField(blank=True, null=True, unique=True)),
                ('follow_up_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('luma_url', models.URLField(blank=True, null=True)),
                ('outreach_prompt', models.TextField(blank=True, help_text='Event-specific base prompt template for message generation.')),
                ('fit_scoring_prompt', models.TextField(blank=True, help_text='Prompt defining the criteria for scoring leads 1-5.')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('reason', models.TextField()),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='RawProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_profile_data', to='contacts.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='follow_up_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.teammember'),
        ),
    ]
