# Generated by Django 5.2.15 on 2026-06-17 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='', unique=True)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, help_text='Company name as text.', max_length=255)),
                ('tier', models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3')], default='Tier 3', max_length=10)),
                ('pipeline_stage', models.CharField(choices=[('Awareness', 'Awareness'), ('First Attendance', 'First Attendance'), ('Engaged', 'Engaged'), ('Deepening', 'Deepening'), ('Activated', 'Activated')], default='Awareness', max_length=30)),
                ('source', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Event', 'Event'), ('Referral', 'Referral'), ('Website', 'Website'), ('Other', 'Other')], default='LinkedIn', max_length=20)),
                ('outreach_status', models.CharField(blank=True, choices=[('Request Sent', 'Request Sent'), ('Connected', 'Connected'), ('Messaged', 'Messaged'), ('No Response', 'No Response'), ('Withdrawn', 'Withdrawn')], default='', max_length=20)),
                ('outreach_owner', models.CharField(blank=True, max_length=100)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('follow_up_due_date', models.DateField(blank=True, null=True)),
                ('follow_up_owner', models.CharField(blank=True, max_length=100)),
                ('follow_up_complete', models.BooleanField(default=False)),
                ('profile_summary', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('personalization_signals', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('mutual_connections', models.TextField(blank=True)),
                ('open_to_work', models.BooleanField(default=False)),
                ('connection_degree', models.CharField(blank=True, max_length=10)),
                ('languages', models.TextField(blank=True)),
                ('organizations', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('key_achievements', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('luma_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('outreach_prompt', models.TextField(blank=True, help_text='Event-specific base prompt template for message generation.')),
                ('fit_scoring_prompt', models.TextField(blank=True, help_text='Prompt defining the criteria for scoring leads 1-5.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('utm_source', models.CharField(blank=True, help_text='UTM tag for outreach tracking.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('fit_score', models.IntegerField(blank=True, help_text='AI calculated fit score (1-5) for this specific event.', null=True)),
                ('fit_reason', models.TextField(blank=True, help_text='AI rationale for fit score.')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='contacts.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='contacts.event')),
            ],
            options={
                'verbose_name_plural': 'attendances',
                'unique_together': {('contact', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=500)),
                ('interaction_type', models.CharField(choices=[('LinkedIn Message', 'LinkedIn Message'), ('Email', 'Email'), ('Meeting', 'Meeting'), ('Call', 'Call'), ('Event Attendance', 'Event Attendance'), ('Other', 'Other')], default='Other', max_length=30)),
                ('date', models.DateField()),
                ('next_action', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OutreachDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1, help_text='Step number in the sequence.')),
                ('generated_text', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Sent', 'Sent')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='contacts.attendance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='contacts.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
