# Generated by Django 5.2.15 on 2026-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
